---
title: "hiv_data_cleaning"
author: "Jake Epstein"
date: "9/19/2019"
output: html_document
---

```{r}
library(dplyr)
library(stringr)
library(shiny)
library(shinythemes)
library(ggplot2)

hiv = read.csv("Archive/hiv_data.csv", stringsAsFactors = FALSE)
hiv = hiv %>%
  select(-X)


for (j in 4:length(hiv)){
  for (i in 1:nrow(hiv)){
    entry = hiv[i,j]
    if (entry == "..."){
      hiv[i,j] = NA
      next
    }
    if (str_count(entry, "<") != 0) {
      hiv[i, j] = 0
    }
    else {
      hiv[i,j] = as.numeric(entry)
    }
  }
}

hiv = hiv %>%
  filter(Country.Code != "")

write.csv(hiv, file = "hiv.csv")
saveRDS(hiv, "hiv.rdata")
```



Add country data and merge with 2018 data
```{r}
country_data = read.csv("countrydata.csv", stringsAsFactors = FALSE)
country_data = country_data %>% mutate(Country = str_trim(Country, side = c("both")))
country_data = country_data %>% rename(SquareArea = Area..sq..mi.., PopulationDensity = Pop..Density..per.sq..mi.., CoastlineRatio = Coastline..coast.area.ratio., NetMigration = Net.migration, InfantMortality = Infant.mortality..per.1000.births., GDPperCapita = GDP....per.capita., Literacy = Literacy...., PhoneOwnership = Phones..per.1000., Arable = Arable...., Crops = Crops...., Other = Other....)
country_variables = colnames(country_data)
hiv_2018 = hiv %>%
  filter(Year == 2018) %>% 
  mutate(Country = str_trim(Country, side = c("both")))
country_data = inner_join(country_data, hiv_2018, by = "Country")
```


```{r, spotify shiny}
shinyApp(
  ui = fluidPage(
    titlePanel("HIV Analysis"),
    theme = shinytheme("darkly"),
    sidebarLayout(
      sidebarPanel = sidebarPanel(
      selectInput(inputId = "selector",
                  label = "Select Variable:",
                  choices = country_variables[3:length(country_variables)],
      hr())),
      mainPanel = mainPanel(plotOutput(outputId = "scatter")))), 
  server = function(input, output, session){
    #output$scatter = renderPlot({ggplot(country_data, aes(x=numeric(input$selector), y=All.ages.incidence.rate..per.1000.)) + geom_point()})
    tableOutput
      })
```
