---
title: "HIV Visualization"
author: "Daniel Spottiswood"
date: "9/21/2019"
output: html_document
runtime: shiny
---

Add country data and merge with 2018 data
```{r}
library(dplyr)
library(stringr)

hiv_data = read.csv("our_world.csv", stringsAsFactors = FALSE)
country_data = read.csv("countrydata.csv", stringsAsFactors = FALSE, dec = ",")
country_data = country_data %>% 
  mutate(Country = str_trim(Country, side = c("both")))

country_data = country_data %>% 
  rename(SquareArea = Area..sq..mi.., PopulationDensity = Pop..Density..per.sq..mi..,
         CoastlineRatio = Coastline..coast.area.ratio., NetMigration = Net.migration,
         InfantMortality = Infant.mortality..per.1000.births., GDPperCapita = GDP....per.capita.,
         Literacy = Literacy...., PhoneOwnership = Phones..per.1000., Arable = Arable....,
         Crops = Crops...., Other = Other....) 

country_variables = colnames(country_data)

regions = unique(country_data$Region)

hiv_data_2017 = hiv_data %>%
  filter(Year == 2017) %>% 
  mutate(Country = str_trim(Entity.x, side = c("both"))) %>%
  rename(Deaths = Deaths.from.HIV.AIDS..Number., NewInfections =  New.infections.of.HIV.AIDS..new.cases.of.HIV.infection.,
         CurrentlyInfected = Number.of.people.living.with.HIV..x10...tens.of.people.living.with.HIV.)

country_data = inner_join(country_data, hiv_data_2017, by = "Country")
```


```{r}
library(ggplot2)
library(shiny)
library(shinythemes)
options(scipen=10000)
shinyApp(
  ui = fluidPage(
    titlePanel("HIV Analysis"),
    theme = shinytheme("yeti"),
    sidebarLayout(
      sidebarPanel = sidebarPanel(
      selectInput(inputId = "selector",
                  label = "Select Variable:",
                  choices = country_variables[4:length(country_variables)],
      hr()),
      selectInput(inputId = "outcome",
                  label = "Select Metric:",
                  choices = c("Deaths", "NewInfections", "CurrentlyInfected"),
      hr()),
      checkboxGroupInput(inputId = "region", 
                         label = "Select Region(s):", 
                         choices = c(regions),
    
      hr()),
      actionButton("action", "Generate Plot"), 
      downloadButton("downloadData", "Download")),
      mainPanel = mainPanel(
        tabsetPanel(tabPanel(title = "Visualization", plotOutput("scatter"), textOutput("interpretation")), 
                    tabPanel(title = "Top 10 Countries", plotOutput("bar"), plotOutput("bar_selector")),
                    tabPanel(title = "Data",dataTableOutput(outputId = "table")
          ))))), 
  
  server = function(input, output){
     state = reactiveValues(
      observers = list()
    )
    
    #when actionbutton is clicked
    observeEvent({
      input$action
      }, {
      # Destroy existing observers
      for(i in seq_along(state$observers)) {
        state$observers[[i]]$destroy()
      }
        
      regionset = country_data %>%
         filter(Region %in% input$region)
  
      output$scatter = renderPlot({
         x = regionset[[input$selector]]
         y = regionset[[input$outcome]]
       
       if(nrow(regionset)==0){
         ggplot(data = country_data) +
           ylab(input$outcome) +
           xlab(input$selector) + 
           geom_blank(show.legend = FALSE) + 
           ggtitle("Please select region(s)")
         
        } else {
         ggplot(data = regionset, aes(x= x, y=y, na.rm = TRUE)) +
           geom_point(aes(colour = factor(regionset$Region), size=Population)) +
           ylab(input$outcome) +
           xlab(input$selector) +
           geom_smooth(method='lm',formula=y~x) +
           labs(color="Region") +
           ggtitle(paste(paste(input$outcome, " VS "), input$selector)) +
           theme_minimal()
         }
      })
      
    output$interpretation = renderText({
      regression = lm((regionset %>% select(input$outcome) 
                        %>% unlist()) ~ (regionset %>% select(input$selector) %>% unlist()))
      coef = summary(regression)$coefficients[2,1]
      p_value = summary(regression)$coefficients[2,4]
      if(p_value < .05){
        paste("We see a significant linear relationship between ", input$selector, " and ",input$outcome, " for the regions selected. A one unit increase in ", input$selector, " is associated with a change in ", input$outcome, " of ", signif(coef,digits = 2), " units for these regions. This is statistically significant at a p-value of ", signif(p_value,digits = 2), ".")
      }
      else{
        paste("Fitting a linear regression, we see a one unit increase in ", input$selector, " is associated with a change in ", input$outcome, " of ", signif(coef,digits = 2), " units for these regions. However, this relationship is not statistically significant with a p-value of ", signif(p_value,digits = 2), ".")
      }
    })
     
    output$bar = renderPlot({
       
    top10 =  regionset %>%
          top_n(10, select(regionset, input$outcome))
    a = top10[["Country"]]
    b = top10[[input$outcome]]
       
     if(nrow(top10)==0){
         ggplot(data = country_data) +
           ylab(input$outcome) +
           xlab(input$selector) + 
           geom_blank(show.legend = FALSE) + 
           ggtitle("Please select region(s)")
         
        } else {

          ggplot(data=top10, aes(reorder(a, -b), b, na.rm = TRUE))+
            ylab(input$outcome) +
            xlab("Country") +
            geom_bar(stat="identity", aes(fill = factor(top10$Region))) +
            labs(fill ="Region") +
            ggtitle(paste("Top 10 Countries for", input$outcome)) +
            theme_minimal() +
            theme(axis.text.x=element_text(angle=45,size = 10,vjust=0.5))
         }
      })
    
    output$bar_selector = renderPlot({
       
    top10 =  regionset %>%
          top_n(10, select(regionset, input$selector))
    a = top10[["Country"]]
    b = top10[[input$selector]]
       
     if(nrow(top10)==0){
         ggplot(data = country_data) +
           ylab(input$selector) +
           xlab("Country") + 
           geom_blank(show.legend = FALSE) + 
           ggtitle("Please select region(s)")
         
        } else {

          ggplot(data=top10, aes(reorder(a, -b), b, na.rm = TRUE))+
            ylab(input$selector) +
            xlab("Country") +
            geom_bar(stat="identity", aes(fill = factor(top10$Region))) +
            labs(fill ="Region") +
            ggtitle(paste("Top 10 Countries for", input$selector)) +
            theme_minimal() +
            theme(axis.text.x=element_text(angle=45,size = 10,vjust=0.5))
         }
      })
    
    output$table =renderDataTable({
    regionset %>% select(Country, Region, input$selector, input$outcome)
    })
    
    output$downloadData <- downloadHandler(
    filename = function() {
      paste("hiv_data_", input$selector, "vs", input$outcome, ".csv", sep = "")
    },
    content = function(file) {
      write.csv(regionset, file, row.names = FALSE)
    }
  )

      }
    )
  }
)
```